---
# tasks file for react-python

##Installing NodeJS
- name: Check if Node is installed
  command: "node --version"
  register: node_check

- name: Install Node
  command: "brew install node"
  when: node_check.stdout != "v12.10.0"

- name: create project folder
  command: "mkdir ~/{{ project_name }}"

- name: Install react
  command: "npx create-react-app {{ project_name }}-frontend"
  args:
    chdir: "~/{{ project_name }}"

- import_tasks: react-starter.yml

- import_tasks: flask-starter.yml

- import_tasks: mongodb-starter.yml

- name: Open up project in visual code
  command: code .
  args:
    chdir: "~/{{ project_name }}/{{ project_name }}-frontend"

- name: Open up project in visual code
  command: code .
  args:
    chdir: "~/{{ project_name }}/{{ project_name }}-backend"

- name: Start the App
  async: 60
  poll: 0
  shell: npm start
  args:
    chdir: "~/{{ project_name }}/{{ project_name }}-frontend"
  register: appstart

- name: Validating the port is open
  tags: nodevalidate
  wait_for:
    host: "localhost"
    port: 3000
    delay: 10
    timeout: 30
    state: started
    msg: "React app is not running"

- name: Git init
  command: git init
  args:
    chdir: "~/{{ project_name }}"

- name: Git add
  command: git add .
  args:
    chdir: "~/{{ project_name }}"

- name: Git commit
  command: git commit -m "initial commit"
  args:
    chdir: "~/{{ project_name }}"
