---
- name: Navigate to project folder
  command: cd ~/{{ project_name }}/{{ project_name }}-frontend

# - name: Install react bootstrap
#   command: "npm install react-bootstrap bootstrap"

# - name: Install material ui
#   command: "npm install @material-ui/core"

# - name: Install styled components
#   command: "npm install styled-components@beta"

# - name: Install redux
#   command: "npm install --save react-redux"

- name: Install common react libraries
  npm: name={{ item }} state=present global=yes
  with_items:
    - react-bootstrap
    - bootstrap
    - "@material-ui/core"
    - "styled-components@beta"
    - "react-redux"
